name: Main workflow

on:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
        ocaml-compiler:
          - 4.13.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pandoc
        run: brew install pandoc

      - name: Install Calibre
        run: sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin

      - name: Install LaTeX dependencies
        run: sudo apt-get update && sudo apt-get -y install texlive-science texlive-font-utils

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: ${{ matrix.os != 'macos-latest' }}

      - name: Install dune
        if: ${{ matrix.os == 'macos-latest' }}
        run: opam install dune>=2.9.0

      - name: Build book
        if: runner.os == 'Linux'
        run: opam exec -- dune build

      - name: Upload artifacts (html, pdf, md, tex)
        uses: actions/upload-artifact@v2
        with:
          path: ./_build/default/static

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: book.pdf
          path: ./_build/default/static/book.pdf
          
      - name: Convert to EPUB
        run: pandoc book.md -o book.epub

      - name: Convert to MOBI
        run: ebook-convert book.epub book.mobi

      - name: Upload EPUB artifact
        uses: actions/upload-artifact@v2
        with:
          name: book.epub
          path: ./_build/default/static/book.epub

      - name: Upload MOBI artifact
        uses: actions/upload-artifact@v2
        with:
          name: book.mobi
          path: ./_build/default/static/book.mobi
